apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo_device_plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: demo_device_plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo_device_plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo_device_plugin
    spec:
      containers:
      - image: demo_device_plugin
        name: demo_device_plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
  updateStrategy:
    type: RollingUpdate